### PR TITLE
move sections for KKP master and update sidebar menu behaviour

### PR DESCRIPTION
**Pull request by serg**

### CODE REVIEW

**Comment by serg** [comment]
fix #839

**Comment by xmudrii** [comment]
@serg I have two concerns about this PR:

* We also need to update `master` docs to the new structure. Otherwise, 2.19 docs will use the old structure because we are always copying from the master docs when cutting a new minor release
  * Note that you can't just copy 2.18 docs to master docs, you'll need to do the reorganization manually. That's because the master docs mostly like already have 2.19 content
* Touching the 2.18 docs means that the old URLs will not work (please correct me if I'm wrong). Since 2.18 is already out for a few months, folks might have references to docs, and after this PR, all those references/links will lead to 404
  * I'd prefer that we only touch master docs, so the new structure is only in effect for 2.19. This means 2.18 will use the old structure, but that sounds safer
  * Redirects might also be possible (and we did that in the past for KubeOne), but it can get pretty complicated when you have a lot of docs, so it's probably better to avoid them

cc @shaase-ctrl

**Comment by serg** [comment]
@xmudrii, your points sounds reasonable.
I thought we need to move sections for current version of docs (v2.18). I didn't find strictly requirements, that this must be only for `master` version.

Therefore, we can revert content changes for v2.18 and move the sections only for `master` branch. Therefore v2.18 will be displaying in previous state. @shaase-ctrl please confirm those actions.

**Comment by serg** [comment]
@xmudrii, the changes were reverted for v2.18 and applied for `master` version. Please check and approve.

**Review by xmudrii — APPROVED** [review]

**Pull request merged**
