### PR TITLE
Fix issue for displaying main logo in firefox

### PR DESCRIPTION
**Pull request by serg**
/assign @xrstf

### CODE REVIEW

**Comment by xrstf** [comment]
@serg please signoff your commits, e.g. by `git commit --amend --signoff && git push --force-with-lease`

**Comment by serg** [comment]
@xrstf thank you for pointing out! Sorry, forgot to do that in this time. Now fixed.

**Comment by serg** [comment]
@xrstf is it possible to merge?

**Comment by serg** [comment]
@xrstf, please see my previous message

**Pull request merged**
