### PR TITLE
Add Dashboard Customization Documentation

### PR DESCRIPTION
**Pull request by kgroschoff**

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@kgroschoff We are working on the same thing for some time now with @floreks. There is an open pull request: https://github.com/kubermatic/docs/pull/529. We have to align this somehow.

**Comment by maciaszczykm** [comment]
Could you take a look on the mentioned pull request and apply your changes there? Do you have any other ideas how to proceed?

**Comment by kgroschoff** [comment]
Oh I haven't seen it, sorry. 
Will add my changes in there and close this PR afterwards. Since we're close to the next release and your PR is quite big, I think it would be good to get it finished and merged in the next days. WDYT?

**Comment by maciaszczykm** [comment]
@kgroschoff Yep, we are working on this actively since yesterday. Hopefully we will be able to finish it together :)

**Comment by kgroschoff** [comment]
Let me know if I could help somewhere

**Comment by maciaszczykm** [comment]
@kgroschoff With OPA :)

**Comment by maciaszczykm** [comment]
Please note, that we've splitted docs into guides and tutorials. The content is not in one place anymore.

**Comment by kgroschoff** [comment]
Checked your PR and it seems everything from here is covered. Will close and continue with the opa part ;)

**Pull request closed without merging**
