### PR TITLE
Update description of the addon form fields

### PR DESCRIPTION
**Pull request by maciaszczykm**
Fixes https://github.com/kubermatic/dashboard/issues/2728.

### CODE REVIEW

**Comment by xrstf** [comment]
This is so useful, I was wondering if we want to backport this into 2.15. @maciaszczykm do you think this is easily possible?

**Comment by maciaszczykm** [comment]
@xrstf I am not sure about the frontend because we were doing quite big refactoring recently. The backend should be easy to merge directly into v2.15.

**Review by xrstf — APPROVED** [review]
Then let's tackle a backport at a later time, if ever.

/approve

**Pull request merged**
