### PR TITLE
Kubeone containerd migration

### PR DESCRIPTION
**Pull request by kron4eg**
Accompaniment docs for https://github.com/kubermatic/kubeone/pull/1362

### CODE REVIEW

**Comment by kron4eg** [comment]
/hold

until kubermatic/kubeone#1362 is merged

**Comment by WeirdMachine** [comment]
You might add this to kubeone v1.3 as well

**Comment by kron4eg** [comment]
@WeirdMachine at the moment it’s pointless

**Comment by kron4eg** [comment]
I mean, when 1.3 will be "released" officially and then we will have docs, and will sync master to v1.3.

**Pull request merged**
