### PR TITLE
Add cypress tests to prow

### PR DESCRIPTION
**Pull request by lindtdev**
Adds an e2e skript that runs the cypress tests and a prow job to execute the script.
Replaces https://github.com/kubermatic/docs/pull/327 which broke after re-forking docs. Fixed the typo.

### CODE REVIEW

**Comment by irozzo-1A** [comment]
@lindtdev Hi Irina, this was not updated since June. Do you think you will be able to work on this in a reasonable time frame? Otherwise, it is probably better to close it.

**Comment by lindtdev** [comment]
@irozzo-1A I will work on this next week.

**Comment by moadqassem** [comment]
@lindtdev Any new updates regarding this ticket? otherwise we either close it or put it to work in progress if you are gonna work on it.

**Comment by lindtdev** [comment]
Still planning to finish it this year, can be put to work in progress.

**Pull request closed without merging**
