### PR TITLE
add MLA customization to the master

### PR DESCRIPTION
**Pull request by aborilov**
fixes: #607

### CODE REVIEW

**Review by jiachengxu — COMMENTED** [review]
Any reasons to put this under `Architecture`?
As I've seen this should either belong to:
- `Tutorial & How-tos/Operation`, this is mentioned in the google docs that Seyi shared during our daily, or
- `Guides` since monitoring page and logging page are already there: https://docs.kubermatic.com/kubermatic/master/guides/installation/logging_stack/
https://docs.kubermatic.com/kubermatic/master/guides/installation/monitoring_stack/

**Comment by aborilov** [comment]
> Any reasons to put this under `Architecture`?
> As I've seen this should either belong to:
> 
> * `Tutorial & How-tos/Operation`, this is mentioned in the google docs that Seyi shared during our daily, or
> * `Guides` since monitoring page and logging page are already there: https://docs.kubermatic.com/kubermatic/master/guides/installation/logging_stack/
>   https://docs.kubermatic.com/kubermatic/master/guides/installation/monitoring_stack/

moved to guides/operation

**Pull request merged**
