### PR TITLE
Fixing typos in faq for dashboard

### PR DESCRIPTION
**Pull request by didier-durand**
Hi there,
As per title
Didier
Signed-off-by: Didier Durand <durand.didier@gmail.com>

### CODE REVIEW

**Review by kron4eg — APPROVED** [review]
/lgtm
/approve

**Comment by didier-durand** [comment]
@kron4eg : Hi, I understand the current hugo failure has to be solved on your side not on mine. Correct?

**Comment by kron4eg** [comment]
@didier-durand yep, sorry for this.

**Comment by didier-durand** [comment]
@kron4eg : no problem. I just wanted to be sure. Didier

**Pull request merged**
