### PR TITLE
Update cilium network policy issue docs

### PR DESCRIPTION
**Pull request by cnvergence**
With 2.24.2 KKP operator creates CiliumClusterwideNetworkPolicy in the seed cluster.
- https://github.com/kubermatic/kubermatic/issues/12874
- https://github.com/kubermatic/kubermatic/pull/12966

### CODE REVIEW

**Review by embik — CHANGES_REQUESTED** [review]
Please also update the `content/kubermatic/main` versions of these document.

**Review by embik — APPROVED** [review]
/approve

/hold
until KKP v2.24.2 has been cut. I will take care of unholding.

**Comment by cnvergence** [comment]
@embik we probably can unhold this now, right?

**Comment by embik** [comment]
/hold cancel

Yes, ofc. Sorry for forgetting about it ...

**Comment by judge-red** [comment]
I think updating this section was missed? https://docs.kubermatic.com/kubermatic/v2.28/installation/install-kkp-ce/add-seed-cluster/#overview

**Pull request merged**
