### PR TITLE
Update aws.en.md

### PR DESCRIPTION
**Pull request by hc2p**
Add missing "elasticloadbalancing:AddTags" permission.

### CODE REVIEW

**Comment by xrstf** [comment]
How does this relate to #1555?

**Comment by hc2p** [comment]
I was not aware of #1555 until now. 
This additional permission here was needed to provision AWS ELBs from a KKP 2.23.6 installation.

**Comment by embik** [comment]
Can you please add this to `main` and `v2.24` for KKP docs as well?

**Comment by xrstf** [comment]
(Note that the file is _index.en.md in those newer docs versions.)

**Review by embik — APPROVED** [review]
/approve

**Comment by xrstf** [comment]
@archups Thank you so, so much for this. Can we now close #1555 as well?

**Comment by archups** [comment]
> @archups Thank you so, so much for this. Can we now close #1555 as well?

#1555 is addressing different issue fix. So IMO, update to the #1555 is required instead of closing it.

**Pull request merged**
