### PR TITLE
Update default applications docs as per 2.25 changes

### PR DESCRIPTION
**Pull request by archups**
Updated images of the default applications to reflect logo, documentlink and sourcecodelink.
Related to https://github.com/kubermatic/kubermatic/pull/13054

### CODE REVIEW

**Comment by xrstf** [comment]
I _tink_ img/common/ was to express "these pictures are used across many products/versions". To add a 2.24 directory _within_ the common directory is kind of ... the opposite of what the directory structure was meant to be... So what's the plan now? To have KKP2.24-specific files in img/common/? What does "common" then mean?

**Comment by archups** [comment]
> I _tink_ img/common/ was to express "these pictures are used across many products/versions". To add a 2.24 directory _within_ the common directory is kind of ... the opposite of what the directory structure was meant to be... So what's the plan now? To have KKP2.24-specific files in img/common/? What does "common" then mean?

@xrstf makes sense. Moved the 2.24 specific images to respective directory now. Thanks!

**Review by embik — APPROVED** [review]
/approve

**Pull request merged**
