### PR TITLE
Add metering docs

### PR DESCRIPTION
**Pull request by simon-wessel**
Signed-off-by: Simon Wessel <simon.wessel@kubermatic.com>
Fixes https://github.com/kubermatic/docs/issues/738

### CODE REVIEW

**Comment by simon-wessel** [comment]
/hold
Preliminary screenshots from https://github.com/kubermatic/dashboard/issues/3589 need to be replaced

**Comment by simon-wessel** [comment]
This is WIP until the screenshots have been replaced. The text can be reviewed though.
/assign @moadqassem 
/assign @WeirdMachine

**Review by moadqassem — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
