### PR TITLE
Update _index.en.md: fix example URL

### PR DESCRIPTION
**Pull request by holgers66**
Fixing a typo in the callback URL example:
https://dex.controlplane.example.com/dex/calback corrected to https://dex.controlplane.example.com/dex/callback

### CODE REVIEW

**Comment by kron4eg** [comment]
@holgers66 can you also please add this to the content/kubeone/master/tutorials/creating_clusters_oidc/_index.en.md so we wouldn't loos it in the future versions doc updates?

**Comment by holgers66** [comment]
Hi @rastislavs. I've created a new PR to merge the fix to master: https://github.com/kubermatic/docs/pull/849

Please feel free to close this PR if needed.

**Comment by kron4eg** [comment]
@holgers66 why not both files in one PR?

**Review by xrstf — APPROVED** [review]
Thanks!

/approve

**Pull request merged**
