### PR TITLE
Add copy behaviour for header anchors

### LINKED ISSUE #1003: Anchors on headlines
every headline should 
- have a hover effect on the headline, making it a different color and have `copy to clipboard` tooltip appear
- have copy on click function 
- have an anchor built in that the link points to

### PR DESCRIPTION
**Pull request by serg**
fix #1003

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
I don't have much idea how our docs website works under the hood, so it's maybe better to see with the UI folks for a review. Anyways, this seems to work, so I can approve the PR and put it on hold if you want someone else to take a look.

/lgtm
/approve
/hold

**Comment by serg** [comment]
@xmudrii, @cschieder already saw this and labeled with `/lgtm`, but from [there](https://github.com/kubermatic/docs/issues/1003#issuecomment-1197763837)

**Pull request merged**
