### PR TITLE
Add KKP release notes in our docs

### PR DESCRIPTION
**Pull request by embik**
This adds our changelog as release notes to docs.kubermatic.com. This was an idea by @ahmedwaleedmalik.

cc @xmudrii @csengerszabo for opinions on this.

### CODE REVIEW

**Comment by csengerszabo** [comment]
Good idea. Only question I have in mind: should we put this in the root or rather in the architecture/ section? Since all compatibility and versioning related topics are elaborated in the latter.

**Comment by embik** [comment]
> Good idea to add it. Only question I have in mind: should we put this in the root or rather in the architecture/ section? Since all compatibility and versioning related topics are elaborated in the latter.

We discussed this on the sig-documentation channel and people specifically requested it to be in the root directory. I don't have strong opinions on this in any case.

**Comment by xmudrii** [comment]
I agree that adding it to the root directory is perhaps the best place for changelogs. Also, if we do this for KKP, we should also do it for KubeOne.

**Review by csengerszabo — APPROVED** [review]
/lgtm

**Pull request merged**
