### PR TITLE
Add `latest` pseudo-release URL that redirects to the latest release

### LINKED ISSUE #1291: Have a "latest" pseudo-release URL that redirects to the latest release
I'm not sure if this is possible to do in our current structure, but I noticed it's hard to link to the "latest released version" for our docs, which means people tend to either link to "main" (which is a bad choice because it's a development version of the docs) or to a fixed version, which can be outdated quickly.

Any chance we can introduce a "latest" URL that redirects to the latest release? e.g. https://docs.kubermatic.com/kubermatic/latest/installation/install-kkp-ce/ should redirect to https://docs.kubermatic.com/kubermatic/v2.21/installation/install-kkp-ce/ and later to https://docs.kubermatic.com/kubermatic/v2.22/installation/install-kkp-ce.

### PR DESCRIPTION
**Pull request by Waseem826**
Fixes #1291

### CODE REVIEW

**Comment by serg** [comment]
lgtm
/assign @embik

**Review by embik — APPROVED** [review]
/approve

Thank you!

**Pull request merged**
