### PR TITLE
Add cookie banner

### PR DESCRIPTION
**Pull request by serg**
/assign @KrissiWi

### CODE REVIEW

**Comment by xrstf** [comment]
@KrissiWi The documentation website is static HTML. It _does not set any cookies_. A cookie banner is completely useless, creates friction, annnoys users and is generally pointless anyway.

Let's please not put this in here just so we can say "GDPR? Check."

**Comment by serg** [comment]
@xrstf please note: Google Tag Manager is using on this website. And it adding bunch of scripts (Google Analytics, etc) like we have on general domain. In this case we need to use cookie banner.

As option, we could stretch banner to full width of page and put it at bottom. The height of page will decrease (on desktop view), but users could see all sections on page. The banner hides when user gives consent for it.

**Pull request merged**
