### PR TITLE
KubeOne: Rework the Cluster Reconciliation document

### PR DESCRIPTION
**Pull request by xmudrii**
/assign @kron4eg

### CODE REVIEW

**Comment by kron4eg** [comment]
@xmudrii turns out, the file `static/img/kubeone/master/architecture/cluster_reconciliation/cluster_reconciliation.png` can be placed next to the document it's referred in `content/kubeone/master/architecture/cluster_reconciliation/_index.en.md` and linked as 

```
![Reconciliation Process Flowchart](cluster_reconciliation.png)
```

**Comment by xmudrii** [comment]
@kron4eg I've already fixed it once I saw your PR. PTAL.

**Review by kron4eg — APPROVED** [review]

**Pull request merged**
