### PR TITLE
Update design on homepage

### LINKED ISSUE #583: Landing Page Redesign
Design: https://www.figma.com/file/Q7S2eEoTe3MXBWnwfVSvbe/DOCS?node-id=731%3A1
Docs

### Effects
Hover on boxes: border turns teal, (hover and link should be on the whole box) `#00D9D2`

### Content
@shaase-ctrl please add what text should be used for the product documentation boxes

### Assets

Diagram image to be used:
KubermaticArchitecture 1

Logos sent via slack

Icons are here  https://drive.google.com/drive/u/1/folders/1Lir9GGcqk-Cd8MC2xdtZHKM88WqcYenY

Icon names are respectively, in order: (left side) Auto Scale, Statistik Up, Kubernetes || (right side) Time, Cash, Person

### PR DESCRIPTION
**Pull request by serg**
fix #583

### CODE REVIEW

**Comment by kgroschoff** [comment]
@serg in order to let the test pass, pleased change
`./content/_index.md:51: dependant ==> dependent`

**Comment by serg** [comment]
@kgroschoff thank you for pointing! Done. Please check.

**Review by kgroschoff — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
