### PR TITLE
Made changes in title and description.

### PR DESCRIPTION
**Pull request by rubandeftsoft**

### CODE REVIEW

**Comment by serg** [comment]
@rubandeftsoft, please apply `--signoff` option when you do every commit. I assumed you are adding the updates through GitHub.
In this case, please define `Signed-off-by` text with options to your commit. Here is example how it should looks:

**Comment by rubandeftsoft** [comment]
> @rubandeftsoft, please apply `--signoff` option when you do every commit. I assumed you are adding the updates through GitHub. In this case, please define `Signed-off-by` text with options to your commit. Additional info in [contributing guide](https://github.com/kubermatic/docs/blob/master/CONTRIBUTING.md#certificate-of-origin). Here is example how it should looks: 

Sure, will do that. Thank you!

**Comment by embik** [comment]
What's the motivation behind this change? Both the URL and the "Product" selection on that page already signal it's the Kubeone documentation, and the description is lifted from the text, but does not seem to accurately describe the page content, as it's more than just the diagram.

**Comment by serg** [comment]
@embik, these updates for improving SEO and displaying the pages in search results. Also, this data will be used when sharing documentation links.

**Comment by embik** [comment]
@serg I can understand that, but this PR is not up to certain standards (non-standard apostrophe usage, description copied from text but insufficient to describe the document's contents) and makes our docs inconsistent (as the KKP architecture docs do not have the product name in the title either).

**Comment by rubandeftsoft** [comment]
> @serg I can understand that, but this PR is not up to certain standards (non-standard apostrophe usage, description copied from text but insufficient to describe the document's contents) and makes our docs inconsistent (as the KKP architecture docs do not have the product name in the title either).

Hi @embik Naveen this side and I am handling SEO stuff for documentation website. This was just for a trial to understand the process of Github. 

Rest, I am preparing a detailed report where I am creating SEO friendly meta description and title for every single landing pages and will share with Kristin for final approval. 

Actually, we need to take care about the standard length of Google to create title and descriptions (title length: 55-60 characters, description length: 150-160 characters). 

I will share final doc file with you guys once I will be done with it. After your approval I will update on specific website's landing page and will send you PRs. Thank you!

**Comment by embik** [comment]
Understood, thanks for the clarification. I was clearly missing context. I wasn't aware this was a test PR. Sorry about the fuzz.

**Pull request closed without merging**
