### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by modularTaco**

### CODE REVIEW

**Comment by youssefazrak** [comment]
@modularTaco thanks for your PR, much appreciated! 
Any possibility of doing this change for 2.14 also? I can see we have the same typo.

**Comment by modularTaco** [comment]
@youssefazrak I've fixed the typo in v2.12 and v2.14 now.

Sorry, i was just at the docs website, saw it and hit the `Edit this page` button, i've not checked that i was at the latest version.  
In v2.15 the typo was already fixed.

**Comment by youssefazrak** [comment]
Thanks again for your contribution @modularTaco 
/lgtm

**Pull request merged**
